"""
app.py
──────
Flask backend for the UCSD Heat Study dashboard.

Receives:
  POST /api/temperature  — from Windows laptop (Arduino sensor)
  POST /api/location     — from iPhone Overland app (direct GPS)
                           OR from MacBook gps_tracker.py (fallback)

Serves:
  GET  /api/data         — raw streams (temp + location separately)
  GET  /api/unified      — interpolated unified timeline + green space lookup
  GET  /api/stats        — session summary statistics
  GET  /                 — dashboard HTML

Run:
    pip install flask
    python app.py

Make sure ucsd_greenspace_coords.csv is in the same folder
(generated by running ucsd_greenspace.py first).
"""

from flask import Flask, jsonify, render_template, request
import os
import csv
import math
import time
from datetime import datetime, timezone

app = Flask(__name__)

# ── In-memory data stores ─────────────────────────────────────────────────
temp_readings     = []
location_readings = []

# ── Green space lookup ────────────────────────────────────────────────────
GREEN_SPACE_CSV    = "ucsd_greenspace_coords.csv"
green_space_points = []

def load_green_space():
    global green_space_points
    if not os.path.exists(GREEN_SPACE_CSV):
        print(f"⚠  Green space CSV not found: {GREEN_SPACE_CSV}")
        print("   Run ucsd_greenspace.py first to generate it.")
        return
    with open(GREEN_SPACE_CSV, newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            green_space_points.append((
                float(row['latitude']),
                float(row['longitude']),
                int(row['is_green'])
            ))
    print(f"✓ Loaded {len(green_space_points):,} green space reference points")


def is_green_at(lat, lon):
    if not green_space_points:
        return None
    best_dist  = float('inf')
    best_green = 0
    for (pt_lat, pt_lon, is_green) in green_space_points:
        dist = math.sqrt((lat - pt_lat)**2 + (lon - pt_lon)**2)
        if dist < best_dist:
            best_dist  = dist
            best_green = is_green
    return bool(best_green)


def interpolate_location(unix_ts):
    if not location_readings:
        return None, None
    sorted_locs = sorted(location_readings, key=lambda x: x.get('unix_time', 0))
    before = [l for l in sorted_locs if l.get('unix_time', 0) <= unix_ts]
    after  = [l for l in sorted_locs if l.get('unix_time', 0) >= unix_ts]
    if not before and not after:
        return None, None
    if not before:
        loc = after[0]
        return loc.get('latitude'), loc.get('longitude')
    if not after:
        loc = before[-1]
        return loc.get('latitude'), loc.get('longitude')
    b   = before[-1]
    a   = after[0]
    t_b = b.get('unix_time', 0)
    t_a = a.get('unix_time', 0)
    if t_a == t_b:
        return b.get('latitude'), b.get('longitude')
    ratio = (unix_ts - t_b) / (t_a - t_b)
    lat   = b['latitude']  + ratio * (a['latitude']  - b['latitude'])
    lon   = b['longitude'] + ratio * (a['longitude'] - b['longitude'])
    return round(lat, 6), round(lon, 6)


# ── Routes ────────────────────────────────────────────────────────────────

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/api/temperature', methods=['POST'])
def receive_temperature():
    data = request.json
    if not data:
        return 'Bad request', 400
    entry = {
        "unix_time":   data.get('timestamp', time.time()),
        "timestamp":   data.get('timestamp', time.time()),
        "temp_c":      data.get('temp_c', data.get('temperature')),
        "temp_f":      data.get('temp_f'),
        "humidity":    data.get('humidity'),
        "heat_event":  data.get('heat_event', 0),
        "temperature": data.get('temp_c', data.get('temperature')),
        "device_name": data.get('device_name', 'Arduino-Thermo'),
    }
    temp_readings.append(entry)
    print(f"[Temp]  {entry['temp_c']}°C | Humidity: {entry['humidity']}% | Heat event: {entry['heat_event']}")
    return 'OK', 200


@app.route('/api/location', methods=['POST'])
def receive_location():
    data = request.json
    if not data:
        return 'Bad request', 400

    # ── Overland app format ───────────────────────────────────────────────
    # {"locations": [{"geometry": {"coordinates": [lon, lat]},
    #                 "properties": {"timestamp": "2026-04-19T...", ...}}]}
    if 'locations' in data:
        for loc in data['locations']:
            coords = loc.get('geometry', {}).get('coordinates', [])
            props  = loc.get('properties', {})
            if len(coords) >= 2:
                ts_str = props.get('timestamp', '')
                try:
                    dt     = datetime.fromisoformat(ts_str.replace('Z', '+00:00'))
                    unix_ts = dt.timestamp()
                except Exception:
                    unix_ts = time.time()
                entry = {
                    "unix_time":   unix_ts,
                    "timestamp":   ts_str,
                    "latitude":    coords[1],   # Overland sends [lon, lat]
                    "longitude":   coords[0],
                    "running_for": "",
                    "device_name": "iPhone-Overland",
                    "speed":       props.get('speed'),
                    "altitude":    props.get('altitude'),
                }
                location_readings.append(entry)
                print(f"[GPS/Overland] Lat: {entry['latitude']:.5f} | Lon: {entry['longitude']:.5f}")
        return 'OK', 200

    # ── Original gps_tracker.py format (fallback) ─────────────────────────
    entry = {
        "unix_time":   data.get('unix_time', time.time()),
        "timestamp":   data.get('timestamp'),
        "latitude":    data.get('latitude'),
        "longitude":   data.get('longitude'),
        "running_for": data.get('running_for'),
        "device_name": data.get('device_name', 'Apple-Watch'),
    }
    location_readings.append(entry)
    print(f"[GPS]   Lat: {entry['latitude']:.5f} | Lon: {entry['longitude']:.5f}")
    return 'OK', 200


@app.route('/api/data', methods=['GET'])
def get_data():
    return jsonify({
        "temperature": temp_readings,
        "location":    location_readings
    })


@app.route('/api/unified', methods=['GET'])
def get_unified():
    unified = []
    for reading in temp_readings:
        ts       = reading.get('unix_time', 0)
        lat, lon = interpolate_location(ts)
        green    = None
        if lat is not None and lon is not None:
            green = is_green_at(lat, lon)
        unified.append({
            "timestamp":  reading.get('timestamp'),
            "unix_time":  ts,
            "temp_c":     reading.get('temp_c'),
            "temp_f":     reading.get('temp_f'),
            "humidity":   reading.get('humidity'),
            "heat_event": reading.get('heat_event'),
            "latitude":   lat,
            "longitude":  lon,
            "is_green":   green,
        })
    return jsonify(unified)


@app.route('/api/stats', methods=['GET'])
def get_stats():
    if not temp_readings:
        return jsonify({"error": "No data yet"})
    temps       = [r['temp_c'] for r in temp_readings if r.get('temp_c') is not None]
    heat_events = sum(1 for r in temp_readings if r.get('heat_event') == 1)
    green_temps     = []
    non_green_temps = []
    for r in temp_readings:
        lat, lon = interpolate_location(r.get('unix_time', 0))
        if lat is not None and lon is not None:
            green = is_green_at(lat, lon)
            if green is True:
                green_temps.append(r['temp_c'])
            elif green is False:
                non_green_temps.append(r['temp_c'])
    return jsonify({
        "total_readings":       len(temp_readings),
        "avg_temp_c":           round(sum(temps) / len(temps), 2) if temps else None,
        "max_temp_c":           max(temps) if temps else None,
        "min_temp_c":           min(temps) if temps else None,
        "heat_events":          heat_events,
        "gps_readings":         len(location_readings),
        "green_avg_temp_c":     round(sum(green_temps) / len(green_temps), 2) if green_temps else None,
        "non_green_avg_temp_c": round(sum(non_green_temps) / len(non_green_temps), 2) if non_green_temps else None,
        "green_space_loaded":   len(green_space_points) > 0,
    })


# ── Startup ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
    load_green_space()
    print("\n✓ Flask server starting on http://0.0.0.0:5000")
    print("  Temperature reader (Windows) → POST /api/temperature")
    print("  Overland app (iPhone)        → POST /api/location")
    print("  Dashboard                    → http://localhost:5000\n")
    app.run(debug=True, host='0.0.0.0', port=5000)
